# Trigger on pushes to master branch
trigger:
  - master

# Use your self-hosted agent pool named "Default"
pool:
  name: Default

steps:
  # 1) Maven build step
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '21.0'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

  # 2) Copy the .war into the artifact staging directory
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/target'
      Contents: '**/*.war'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  # 3) Publish the staged .war as a pipeline artifact
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
